
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gl_core?Unicode=true&characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    networks:
      - gl

  db:
    image: mysql:8.0.26
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=gl_core
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/init.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    networks:
      - gl

volumes:
  db-data:
networks:
  gl:
