

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gl-core?Unicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  mapper-locations:
