

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gl-core?Unicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: gl
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis-plus:
  mapper-locations:

token:
  signing:
    key: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
jwt:
  access:
    expiration:
      ms: 3600000 # 1 hour
#      ms: 60000
  refresh:
    expiration:
      ms: 604800000 # 1 week

knife4j:
  enable: true
  setting:
    language: zh_cn
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.gl.controller
file:
  upload:
    avatar-path: E:/jingtai/gl/avatar