server:
  port: 8989

spring:
  application:
    name: gl-core
  profiles:
    active: dev

# Enable SQL logging
logging:
  level:
    com.gl.mapper: debug

project:
  url: http://localhost:8989/api/v1/file